// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCewV2J3_gGErxkna6P8R2-ceu7VedAfBY',
    appId: '1:138562725000:web:a474326f9e1eeb551bab3d',
    messagingSenderId: '138562725000',
    projectId: 'musihelp-3f0c9',
    authDomain: 'musihelp-3f0c9.firebaseapp.com',
    storageBucket: 'musihelp-3f0c9.firebasestorage.app',
    measurementId: 'G-MK4YRTQPZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAViHHq0abzfYTx-t5_brn3BPO6KvyY-jM',
    appId: '1:138562725000:android:fdfe14b08e1fd1a71bab3d',
    messagingSenderId: '138562725000',
    projectId: 'musihelp-3f0c9',
    storageBucket: 'musihelp-3f0c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNbMdWb1NeXJRbzPxT6V3tceglV9VrPow',
    appId: '1:138562725000:ios:0ad2ce572be5fb381bab3d',
    messagingSenderId: '138562725000',
    projectId: 'musihelp-3f0c9',
    storageBucket: 'musihelp-3f0c9.firebasestorage.app',
    iosBundleId: 'com.musihelp.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNbMdWb1NeXJRbzPxT6V3tceglV9VrPow',
    appId: '1:138562725000:ios:0ad2ce572be5fb381bab3d',
    messagingSenderId: '138562725000',
    projectId: 'musihelp-3f0c9',
    storageBucket: 'musihelp-3f0c9.firebasestorage.app',
    iosBundleId: 'com.musihelp.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCewV2J3_gGErxkna6P8R2-ceu7VedAfBY',
    appId: '1:138562725000:web:abdcaf4b08229a221bab3d',
    messagingSenderId: '138562725000',
    projectId: 'musihelp-3f0c9',
    authDomain: 'musihelp-3f0c9.firebaseapp.com',
    storageBucket: 'musihelp-3f0c9.firebasestorage.app',
    measurementId: 'G-0QE057J4DF',
  );
}
